# Generated by Django 4.0.1 on 2022-02-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewshop', '0005_alter_product_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('goods_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewshop.product')),
            ],
        ),
    ]
