# Generated by Django 4.0.1 on 2022-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewshop', '0002_alter_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank='true', upload_to='media'),
        ),
    ]
