# Generated by Django 4.0.1 on 2022-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_story', models.IntegerField(default=0, unique=True, verbose_name='Story identificator')),
                ('by', models.CharField(max_length=200, verbose_name='Author')),
                ('score', models.IntegerField(default=0)),
                ('descendants', models.IntegerField(default=0)),
                ('kids', models.TextField(default='No content')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(default='No content')),
                ('time', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_story', models.IntegerField(default=0, unique=True, verbose_name='Story identificator')),
                ('by', models.CharField(max_length=200, verbose_name='Author')),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(default='No content')),
                ('time', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField(default='No content')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_story', models.IntegerField(default=0, unique=True, verbose_name='Story identificator')),
                ('by', models.CharField(max_length=200, verbose_name='Author')),
                ('score', models.IntegerField(default=0)),
                ('descendants', models.IntegerField(default=0)),
                ('kids', models.TextField(default='No content')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(default='No content')),
                ('time', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField(default='No content')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_story', models.IntegerField(default=0, unique=True, verbose_name='Story identificator')),
                ('by', models.CharField(max_length=200, verbose_name='Author')),
                ('score', models.IntegerField(default=0)),
                ('descendants', models.IntegerField(default=0)),
                ('kids', models.TextField(default='No content')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(default='No content')),
                ('time', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField(default='No content')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
