# Generated by Django 4.0.1 on 2022-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=250, verbose_name='Category name'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
